[swarm_managers]
manager1  ansible_host=127.0.0.1  ansible_user=yaromyrm  ansible_connection=local

[docker_hosts:children]
swarm_managers

[all:vars]
ansible_python_interpreter=/Users/yaromyrm/ansible-venv/bin/python3
docker_registry=127.0.0.1:6578
app_image_name=hello-world-app
app_image_tag=latest
